apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email:  oveldman@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-prod
    solvers:
      - http01:
          ingress:
            class: public
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: madworld-ingress
  namespace: madworld
  annotations:
    cert-manager.io/cluster-issuer: "lets-encrypt"
    cert-manager.io/common-name: "www.mad-world.nl"
    cert-manager.io/subject-countries: "NL"
    cert-manager.io/email-sans: "oveldman@gmail.com"
    kubernetes.io/ingress.class: "public"
spec:
  tls:
    - hosts:
        - admin.mad-world.nl
        - api.mad-world.nl
        - identity.mad-world.nl
        - log.mad-world.nl
        - www.mad-world.nl
      secretName: madworld-tls
  rules:
    - host: admin.mad-world.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: madworld-admin-loadbalancer
                port:
                  number: 80
    - host: api.mad-world.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: madworld-api-loadbalancer
                port:
                  number: 80
    - host: identity.mad-world.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: madworld-identity-loadbalancer
                port:
                  number: 80
    - host: log.mad-world.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seq-loadbalancer
                port:
                  number: 80
    - host: www.mad-world.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: madworld-ui-loadbalancer
                port:
                  number: 80