apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: madworld-ingress
  namespace: madworld
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-For $http_x_forwarded_for";
spec:
  rules:
    - host: admin.mad-world.local
      http:
        paths:
          - path: "/((.*(?:css|css.map|html|js|json|png)$))|(.*)"
            pathType: Prefix
            backend:
              service:
                name: madworld-admin-loadbalancer
                port:
                  number: 80
    - host: api.mad-world.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: madworld-api-loadbalancer
                port:
                  number: 80
    - host: identity.mad-world.local
      http:
        paths:
          - path: "/((.*(?:css|css.map|html|js|json|png)$))|(.*)"
            pathType: Prefix
            backend:
              service:
                name: madworld-identity-loadbalancer
                port:
                  number: 80
    - host: log.mad-world.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seq-loadbalancer
                port:
                  number: 80
    - host: shipsimulator.mad-world.local
      http:
        paths:
          - path: "/((.*(?:css|css.map|html|js|json|png)$))|(.*)"
            pathType: Prefix
            backend:
              service:
                name: madworld-shipsimulator-frontend-loadbalancer
                port:
                  number: 80
    - host: shipsimulator-api.mad-world.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: madworld-shipsimulator-backend-loadbalancer
                port:
                  number: 80
    - host: www.mad-world.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: madworld-ui-loadbalancer
                port:
                  number: 80