apiVersion: apps/v1
kind: Deployment
metadata:
  name: madworld-admin-deployment
  namespace: madworld
  labels:
    app: madworld-admin
    name: frontend-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madworld-admin
      task: frontend-admin
  template:
    metadata:
      labels:
        app: madworld-admin
        task: frontend-admin
    spec:
      containers:
        - name: madworld-admin
          image: madworld/vps/admin:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: madworld-admin-loadbalancer
  namespace: madworld
spec:
  selector:
    app: madworld-admin
    task: frontend-admin
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 80
  type: LoadBalancer