apiVersion: apps/v1
kind: Deployment
metadata:
  name: madworld-ui-deployment
  namespace: madworld
  labels:
    app: madworld-ui
    name: frontend-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madworld-ui
      task: frontend-ui
  template:
    metadata:
      labels:
        app: madworld-ui
        task: frontend-ui
    spec:
      containers:
        - name: madworld-ui
          image: madworld/vps/ui:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: madworld-ui-loadbalancer
  namespace: madworld
spec:
  selector:
    app: madworld-ui
    task: frontend-ui
  ports:
    - protocol: TCP
      name: http
      port: 8086
      targetPort: 80
  type: LoadBalancer